/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#25005a",
        "on-secondary-container": "#fffbff",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed-variant": "#004e5c",
        "primary-fixed-dim": "#bbc3ff",
        "tertiary-container": "#006a7c",
        "on-error": "#ffffff",
        "primary": "#2036bd",
        "outline": "#757686",
        "on-primary": "#ffffff",
        "error-container": "#ffdad6",
        "tertiary-fixed-dim": "#4cd7f6",
        "surface-dim": "#d8dadc",
        "surface-container-highest": "#e0e3e5",
        "surface-tint": "#3b4fd2",
        "on-surface": "#191c1e",
        "on-primary-container": "#d7daff",
        "on-primary-fixed": "#000d60",
        "surface-variant": "#e0e3e5",
        "tertiary": "#00505f",
        "on-surface-variant": "#454654",
        "on-primary-fixed-variant": "#1d34ba",
        "secondary": "#712ae2",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed-variant": "#5a00c6",
        "primary-container": "#3e52d5",
        "on-error-container": "#93000a",
        "primary-fixed": "#dfe0ff",
        "inverse-primary": "#bbc3ff",
        "surface-bright": "#f7f9fb",
        "error": "#ba1a1a",
        "tertiary-fixed": "#acedff",
        "secondary-container": "#8a4cfc",
        "inverse-on-surface": "#eff1f3",
        "on-background": "#191c1e",
        "surface-container": "#eceef0",
        "surface": "#f7f9fb",
        "surface-container-low": "#f2f4f6",
        "on-tertiary-container": "#94e8ff",
        "surface-container-high": "#e6e8ea",
        "inverse-surface": "#2d3133",
        "on-tertiary-fixed": "#001f26",
        "background": "#f7f9fb",
        "secondary-fixed": "#eaddff",
        "secondary-fixed-dim": "#d2bbff",
        "outline-variant": "#c5c5d7",
        "on-tertiary": "#ffffff"
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
        manrope: ["Manrope", "sans-serif"],
      },
    },
  },
  plugins: [],
}
